title: The title.
description: The description.

# Theme
remote_theme: just-the-docs/just-the-docs

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Enable the search bar
search_enabled: true

# Navigation Settings
back_to_top: true
back_to_top_text: "Back to top"
heading_anchors: true

# Color Scheme (Optional)
color_scheme: light
